# fly.toml app configuration file generated for buildorboom on 2025-08-05T16:37:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'buildorboom'
primary_region = 'sea'

[build]

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
max_machines_running = 1
min_machines_running = 0

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
